### ISSUE TITLE
Relative index scrolling

### ISSUE THREAD

**Issue by eggzotic** [quire-io/scroll-to-index#10]
I've just implemented a sample Flutter app (https://github.com/eggzotic/scroll_to_index_sample) with this and am loving it - also managed to use Stateless Widgets throughout, with a little help from Provider package.

Problem: how to "scroll back/forward X (e.g. X=15) rows", if the user has already manually scrolled (using their finger!) so that the visible rows are no longer tracked by the controller? Can we reverse map from the controller current position (pixels) to the row-number?

**Comment by jerrywell** [comment]
I believe your question can be solved in the reference of issue #4. the sample i leaved in that flutter issue will help you track the index from the given pixel on the screen. :)

btw, to better the performance, you can trigger the tracking if user press back/forward.

**Comment by eggzotic** [comment]
Thanks for the idea. However I was unable to make that work, partly because I'm using StatelessWidgets only, throughout - so no State objects to work with. However I have come up with a solution, detailed in my updated sample app at https://github.com/eggzotic/scroll_to_index_sample. This uses GlobalKeys on each ListView children item, and then a NotificationListener wrapped around the ListView and updating the scroll-offset from ScrollEndNotification's context. This lets us find the first item that is within the ListView viewport.

No need for MetaData, HitTests or locating the global position of the ListView on the screen.
