### ISSUE TITLE
Scroll to index if not visible

### ISSUE THREAD

**Issue by rablexxx** [quire-io/scroll-to-index#11]
First of all, thanks for your work!
Is it possible to implement an additional method (for example .scrollToIndexIfNotVisible) that will scroll only if the item is not in viewport? Or maybe there is a way to do this already?

Thanks in advance.

**Comment by jerrywell** [comment]
don't put the parameter `preferPosition` into `scrollToIndex()` and the behavior should be the same as your expectation.

https://github.com/quire-io/scroll-to-index/blob/master/lib/scroll_to_index.dart#L193

**Comment by rablexxx** [comment]
Perfect! Works like a charm!
Thank you.
