### ISSUE TITLE
When the ListView scrolls to the bottom, the bottom entry and some of the entries on the bottom cannot be scrolled to the begin position. Is there any good solution?

### ISSUE THREAD

**Issue by gaojuanjuan** [quire-io/scroll-to-index#13]
When the ListView scrolls to the bottom, the bottom entry and some of the entries on the bottom cannot be scrolled to the begin position. Is there any good solution?

**Comment by gaojuanjuan** [comment]
> When the ListView scrolls to the bottom, the bottom entry and some of the entries on the bottom cannot be scrolled to the begin position. Is there any good solution?

![image](https://user-images.githubusercontent.com/14133759/66380872-d06e0100-e9ea-11e9-8026-0f4982403417.png)

**Comment by jerrywell** [comment]
you can try to append a suffix entry as the spacing element for it.

**Comment by gaojuanjuan** [comment]
> you can try to append a suffix entry as the spacing element for it.

I don't understand very well. Can you describe it in detail?

**Comment by gaojuanjuan** [comment]
我看你是中国人，你的意思是添加一些多余的item吗，就是比实际要展示的数据再多添加点？

**Comment by jerrywell** [comment]
you can set one more index for the extra element and add it to the last one of list children in order to push the list up.

**Comment by jerrywell** [comment]
i'm closing this issue for the end of conversation.
