### ISSUE TITLE
InputConnection closed when calling highlight()

### ISSUE THREAD

**Issue by ovidiu-anghelina** [quire-io/scroll-to-index#15]
I have a ModalBottomSheet with a single TextFormField and a button, and the input field gets highlighted when I tap the button. The problem is that the keyboard disappears when I call highlight().

I placed lots of breakpoints to try and understand why, and this is what I found:
After this line of code within your library is reached: `await catchAnimationCancel(_controller.animateTo(1.0, duration: scrollAnimationDuration));` Flutter will unmount all inactive elements (as a result of `setState` being called on the previous line), which for some reason I cannot explain includes my TextFormField as well. In turn, this triggers `_closeInputConnectionIfNeeded()` within `EditableTextState`, which then hides the keyboard because there are no active InputConnections left.

If I replace the call to `highlight()` with a call to `setState()`, the keyboard no longer disappears even though the UI is rebuilt, which means that it's something within your library's code that causes this.

**Comment by jerrywell** [comment]
_closeInputConnectionIfNeeded usually comes with a dispose of TextField, which may be caused by the different widget mounted in different level. if you wanna always keep it shown, you should make sure the textfield will appear in every frame. do you have the minimal reproduce sample?

**Comment by ovidiu-anghelina** [comment]
Minimal sample:

```
import 'package:flutter/material.dart';
import 'package:scroll_to_index/scroll_to_index.dart';

void main() => runApp(MaterialApp(
  home: Builder(
    builder: (BuildContext context) => Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          AutoScrollController controller = AutoScrollController();
          int index = 0;

          showModalBottomSheet(
            context: context,
            builder: (BuildContext context) => Padding(
              padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  ListView(
                    controller: controller,
                    shrinkWrap: true,
                    children: <Widget>[
                      AutoScrollTag(
                        key: ValueKey(index),
                        controller: controller,
                        index: index,
                        highlightColor: Colors.redAccent,
                        child: TextFormField(
                          initialValue: "Tap here 1st",
                        ),
                      ),
                    ],
                  ),
                  RaisedButton(
                    child: const Text("Tap here 2nd"),
                    onPressed: () {
                      controller.highlight(index);
                    },
                  ),
                ],
              ),
            ),
          );
        },
        child: Icon(Icons.add),
      ),
    ),
  ),
));
```

**Comment by ovidiu-anghelina** [comment]
Any update on this?

**Comment by jerrywell** [comment]
sorry for the late reply. this issue is fixed. it's because the build function of AutoScrollTag will generate different widget structure depending on the highlight status, which will cause the underlying widget be disposed. you can upgrade to the 1.0.3 to check if it's fixed. :)
