### ISSUE TITLE
Please migrate sample app to support AndroidX

### ISSUE THREAD

**Issue by anticafe** [quire-io/scroll-to-index#21]
While build app, I notice this warning:
>[!] Your app isn't using AndroidX.
>To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.

So, if it's possible, could you please migrate sample app to AndroidX?
Thanks.

**Comment by jerrywell** [comment]
thanks for this mention. looks it's not a urgent issue, i will migrate it later. :)
