### ISSUE TITLE
Any way to specify the duration of the animation?

### ISSUE THREAD

**Issue by Nais0ne** [quire-io/scroll-to-index#24]
Having a big list of items with dynamic height, sometimes the scrolling animation takes way too long. is there any way too speed it up?

**Comment by jerrywell** [comment]
you can try to give the suggested row height into scroll controller. given any average value is fine, because this library will auto correct the final position even over scrolling.

```
AutoScrollController(
  suggestedRowHeight: 500
  ...
);
```

**Comment by Nais0ne** [comment]
Thank you for your answer ^^

yeah that works. is there any way to specify that in the scrollToIndex function? like scrolling always taking the same amount of time

**Comment by Nais0ne** [comment]
Nevermind, found out that you can pass a duration into that function, works, even tho it looks a bit buggy
