### ISSUE TITLE
 Scrolling does not work if I put a widget wrapped with an AutomaticKeepAlive widget as a child of the AutoScrollTag widget

### ISSUE THREAD

**Issue by qjatjr1108** [quire-io/scroll-to-index#27]
ScrollToIndex does not work if I put a widget wrapped with an AutomaticKeepAlive widget as a child of the AutoScrollTag widget.

What is the correct way, if any, to achieve this?

**Comment by jerrywell** [comment]
`AutomaticKeepAlive` should wrap the whole AutoScrollTag since it's the default setting from Sliverlist. I supposed it won't be added by ourself. can you test like this way and post the sample code if it still failed.
