### ISSUE TITLE
is it possible to use this on ListView.builder ?

### ISSUE THREAD

**Issue by zukinaru** [quire-io/scroll-to-index#3]
my widget will created dynamically using `ListView.builder` , so it's not fixed at beginning.

is it possible to use this plugin ?

thanks

**Comment by jerrywell** [comment]
yes.

```
ListView(
  scrollDirection: scrollDirection,
  controller: controller,
  children: randomList.map<Widget>((data) {
  	final index = data[0];
  	final height = data[1];
    return AutoScrollTag(
      key: ValueKey(index),
      controller: controller,
      index: index,
      child: Text('index: $index, height: $height'),
      highlightColor: Colors.black.withOpacity(0.1),
    );
  }).toList(),
)
```

you should be able to create this kind of children widgets. like the same way, just wrap your widgets inside the children with AutoScrollTag().

**Comment by zukinaru** [comment]
Hi, 
i cant add 👍 

```
children: randomList.map<Widget>((data) {
  	final index = data[0];
  	final height = data[1];
    return AutoScrollTag(
      key: ValueKey(index),
      controller: controller,
      index: index,
      child: Text('index: $index, height: $height'),
      highlightColor: Colors.black.withOpacity(0.1),
    );
  }
```
as a child in `ListView.builder`, there's no option/parameter for `child`

**Comment by jerrywell** [comment]
not sure what your question is. but that is a builder function called "itemBuilder" which returns the widget in the builder constructor.

https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html
https://api.flutter.dev/flutter/widgets/IndexedWidgetBuilder.html

**Comment by nipunasudha** [comment]
> not sure what your question is. but that is a builder function called "itemBuilder" which returns the widget in the builder constructor.
> 
> https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html
> https://api.flutter.dev/flutter/widgets/IndexedWidgetBuilder.html

You didn't answer the question. Can we or can't we use ListView.builder() with your plugin? ListView.builder() does not create the items unless they are currently visible (or about to be). So please confirm your plugins ability to scroll to a list element that's not currently in the widget tree. Plugin document only uses ListView(), thats why the OP is asking about this.

**Comment by jerrywell** [comment]
If you just wanna an answer, as I said YES, you can. 

The builder is just a function getting the index and return the widget according to the given index. It's the same concept compared to the way you give the whole widget list. The only difference is you lazily creat each widget until you need.

**Comment by rockingdice** [comment]
Hmmm. Interesting. I just tested `ListView.builder` and the answer is not always YES.

Basically, the ListView.builder is not the same as ListView default constructor. The items' information are not available when they are not created (position, size , etc). 

You can scroll to the items that are already created, but not when the items are not created.

Imagine I have 100 items. I can scroll to #7 for the first time, but not for #50 because it's not created yet.

If the ListView is already created and scrolled to a specific position - like nearing #40, then you can scroll to #50 at the moment.

It's good for you to test this scenario again and correct me if I'm wrong. Thank you again for making this package.

**Comment by rockingdice** [comment]
Just a reminder, I also used a FutureBuilder for creating an item, maybe it's related too.

**Comment by rockingdice** [comment]
So I've confirmed the issue is caused from `FutureBuilder`, I'll make another issue about it.

**Comment by doradsoft** [comment]
I confirm it does work perfectly with `ListView.builder` in my case

**Comment by MohsenHaydari** [comment]
> I confirm it does work perfectly with `ListView.builder` in my case

it not possible, maybe your listView builder Not loaded correctly, like implement listView.builder in SliverToBoxAdapter, cacheExtend is very large or your list length is very small And all items are reloaded from the first moment
