### ISSUE TITLE
Offset scrollToIndex ?

### ISSUE THREAD

**Issue by HugoHeneault** [quire-io/scroll-to-index#32]
Hi there, 

Nice plugin 👏 

I would like to scroll to an item and use an offset to be more precise. 

In my case I have a nice-looking padding on my scroll container 👍 
![image](https://user-images.githubusercontent.com/4112256/95654967-5512c400-0b04-11eb-956b-b2514db7c7f3.png)

But when I `scrollToIndex` I don't have a way to ask him to scroll 20px before the item, making it looking a bit stuck on the left :

![image](https://user-images.githubusercontent.com/4112256/95654961-46c4a800-0b04-11eb-8cf8-c0b4054b0df6.png)

Is there a way or how would you do it if we have to implement it (I can help)

Thanks !

**Comment by jerrywell** [comment]
You can give a viewport boundary for it. see https://github.com/quire-io/scroll-to-index/blob/master/example/lib/main.dart#L47.

**Comment by HugoHeneault** [comment]
Thanks @jerrywell for your fast answer!

I used 

```
viewPortBoundaryGetter: () => Rect.fromLTRB(20, 0, 0, 0),
        axis: Axis.horizontal)
```

and it worked great! 

It should be more explicit that `viewPortBoundaryGetter` must be used with `axis` to get the `left` boundary. By default the beginGetter is the top one if we don't provide an axis parameter.
