### ISSUE TITLE
Does not scroll to items outside the viewport

### ISSUE THREAD

**Issue by DennisMuchiri** [quire-io/scroll-to-index#33]
Thanj you for this library ...but the scroll controller does not scroll to items outside the viewport

**Comment by DennisMuchiri** [comment]
![CaptureOTHERVIEWPORT](https://user-images.githubusercontent.com/11217100/99639923-50252680-2a59-11eb-8e83-4d6dccbf3b1f.PNG)

**Comment by jerrywell** [comment]
not pretty sure what you mean? 
do you mean the last half white dot doesn't completely being scrolled into the viewport?

**Comment by nipunasudha** [comment]
> not pretty sure what you mean?
> do you mean the last half white dot doesn't completely being scrolled into the viewport?

Dude you are escaping from the issues! He asked about "items outside the viewport". so at least answer that before closing this.

**Comment by jerrywell** [comment]
we need more information about the question. if you can provide the sample, you can post it.

**Comment by DennisMuchiri** [comment]
sorry I had not put AutoScrollTag on my items.. closing
