### ISSUE TITLE
Scrolling to item "above" screen does not work

### ISSUE THREAD

**Issue by amitkot** [quire-io/scroll-to-index#35]

**Comment by jerrywell** [comment]
not sure what you mean? can you explain more detail or steps for it?

**Comment by amitkot** [comment]
Oh, sorry, this issue was added by mistake, I'll close it.
I was having problems scrolling to items higher in the screen. 
After researching the situation I was able to determine that the issue was scrolling in a CustomListView to a sliver within a [MultiSliver](https://pub.dev/documentation/sliver_tools/latest/sliver_tools/MultiSliver-class.html) widget. I will open a separate issue.
Thanks!
