### ISSUE TITLE
I want to be able to relate the left and right sides of how to operate?

### ISSUE THREAD

**Issue by lifetin** [quire-io/scroll-to-index#4]
我希望能关联左右两边该如何操作?
下面的图片中,我在右边滚动时,希望左边能定位到具体位置,该如何操作?
现在我左右点击,能将右边的和左右关联,但是无法在右边滚动时,把左边关联?
------------------------------------------------------------------------------------------
I want to be able to relate the left and right sides of how to operate?
In the following picture, when I scroll on the right side, I hope that the left side can be positioned to the specific location. How to operate?
Now I can click right and left to associate right and left, but can't scroll right to associate left?

![44](https://user-images.githubusercontent.com/10474968/59518484-4d371580-8ef8-11e9-8724-019230b5c236.png)

**Comment by jerrywell** [comment]
you can try this solution when scroll position is changed. that is, just check the beginning/end of viewport to determine which section you wanna highlight.
https://github.com/flutter/flutter/issues/19941#issuecomment-486950990
