### ISSUE TITLE
Make method to retrieve offset of widget public in AutoScrollController

### ISSUE THREAD

**Issue by bejaeger** [quire-io/scroll-to-index#43]
Hi,

first of all, thanks for providing this package, this saved me a lot of time. I'm using the `AutoScrollController` in a `CustomScrollVIew`. I would like to change the opacity of a widget dependent on the scroll position. Is it possible to retrieve the offset of a specific index tagged with `AutoScrollTag` so I don't have to calculate the position myself? It seems like this feature must be already implemented in the AutoScrollController and would just be needed to make public.

Thanks in advance.
Benjamin!

**Comment by jerrywell** [comment]
you can refer to the thread and this comment: https://github.com/quire-io/scroll-to-index/issues/26#issuecomment-608998845
