### ISSUE TITLE
Overlay highlight color

### ISSUE THREAD

**Issue by ojm-it** [quire-io/scroll-to-index#45]
Currently, the highlight color appears behind the child widget of `AutoScrollTag`.
So if the said widget has a background color, it will cover the highlight color.

Here is an example where the highlight color is red. We can barely see it at the edges.

![image](https://user-images.githubusercontent.com/80984705/114621337-1d93f880-9c9c-11eb-84f3-83f4d5a5d2bc.png)

Is there any way for the highlight to be overlaid on top of the child widget? 

Thank you.

**Comment by ojm-it** [comment]
Actually, a better example would be if the child of `AutoScrollTag` is an image.

**Comment by jerrywell** [comment]
usage example:

```
AutoScrollTag(
  key: ValueKey(0),
  controller: _scrollController,
  index: 0,
  builder: (BuildContext context, Animation<double> highlight) {
    return DecoratedBoxTransition(
      position: DecorationPosition.foreground,
      decoration: DecorationTween(
        begin: BoxDecoration(),
        end: BoxDecoration(color: Colors.blue.withOpacity(0.3))
      ).animate(highlight),
      child: Container(
        height: 320.0,
        color: Colors.yellow,
      )
    );
  }
)
```
