### ISSUE TITLE
FutureBuilder items cannot be properly scrolled to

### ISSUE THREAD

**Issue by rockingdice** [quire-io/scroll-to-index#46]
As the title suggests, the items that are created by the `FutureBuilder` cannot be scrolled to correctly.

It's relatively useful if the item is complex and need more time to build. 

Can you please check if the package can support it?

**Comment by jerrywell** [comment]
can you provide the reproduce example? technically future builder will finally return widget and to be displayed in the list.

**Comment by rockingdice** [comment]
Sadly, I'm too busy to make a repro for you. But I think it's not hard to make one, just wrap the child inside a `FutureBuilder`, and make the list fairly long enough to scroll. But I'll find spare time to make one for you eventually.

**Comment by sinhpn92** [comment]
I do not use FutureBuilder, but I still cannot scroll to index.
I have got this error:
```
E/flutter ( 5113): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:scroll_to_index/scroll_to_index.dart': Failed assertion: line 381 pos 14: '(offsetToLastState?.offset ?? 0) >= 0': ERROR: %%%%%%%%%%%%%%: 17, 5, 1.0, RevealedOffset(offset: -13.0, rect: Rect.fromLTRB(0.0, 560.0, 752.6, 591.0)), 1,5
E/flutter ( 5113): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 5113): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 5113): #2      AutoScrollControllerMixin._forecastMoveUnit (package:scroll_to_index/scroll_to_index.dart:381:14)
E/flutter ( 5113): #3      AutoScrollControllerMixin._scrollToIndex (package:scroll_to_index/scroll_to_index.dart:271:13)
E/flutter ( 5113): <asynchronous suspension>
E/flutter ( 5113): #4      co.then (package:scroll_to_index/util.dart)
E/flutter ( 5113): <asynchronous suspension>
E/flutter ( 5113): 

```

**Comment by jerrywell** [comment]
@sinhpn92 the index number of `AutoScrollTag` must be the sequential value, e.g. 0, 1, 2, 3, 4....n, n+1. not sure if this is the root cause of your issue.
