### ISSUE TITLE
Duration in scrollToIndex is ignorred

### ISSUE THREAD

**Issue by pro100svitlo** [quire-io/scroll-to-index#47]
I found this issue with lists with many items (long ones).

In this case, when I scroll to some item close to the bottom, it doesn't matter what duration I set via method - it still takes a looong time to scroll, which is definitely more than my duration.

**Comment by jerrywell** [comment]
sorry to hear that, but it's the limitation of this package for very long list. : (
please refer to this thread https://github.com/quire-io/scroll-to-index/issues/44 for more detail.
