### ISSUE TITLE
How to get current list item Index on scroll?

### ISSUE THREAD

**Issue by imSanjaySoni** [quire-io/scroll-to-index#50]

**Comment by jerrywell** [comment]
dup of https://github.com/quire-io/scroll-to-index/issues/40

**Comment by imSanjaySoni** [comment]
```dart
void listenPosition() {
  final scrollController = state.scrollController;
  scrollController.addListener(() {
    final int currentIndex = scrollController.currentTagIndexInViewport(
        preferPosition: AutoScrollPosition.begin);
    AutoScrollTagState asts = scrollController.tagMap[currentIndex];
  });
}

```


A value of type 'dynamic' can't be assigned to a variable of type 'int'.
Try changing the type of the variable, or casting the right-hand type to 'int'.dart(invalid_assignment)
The method 'currentTagIndexInViewport' isn't defined for the type 'AutoScrollController'.
Try correcting the name to the name of an existing method, or defining a method named 'currentTagIndexInViewport'.dart(undefined_method)

**Comment by jerrywell** [comment]
tried this way. https://github.com/flutter/flutter/issues/19941#issuecomment-486950990

**Comment by imSanjaySoni** [comment]
> try this way. [flutter/flutter#19941 (comment)](https://github.com/flutter/flutter/issues/19941#issuecomment-486950990)

@jerrywell  could you please explain this in simpler way.  I am not getting it, or can you tag other example.
