### ISSUE TITLE
Offer a jumpToIndex()

### ISSUE THREAD

**Issue by rocboronat** [quire-io/scroll-to-index#53]
There's only a scrollToIndex() method. To have an inmediate scroll, I thought I could use duration: Duration.zero, but it launches a `Failed assertion: line 216 pos 12: 'duration > Duration.zero': is not true.`

So may you offer a jumpToIndex() method?

Thanks a lot!

**Comment by na2axl** [comment]
Hello there, @jerrywell no thoughts on this? A `jumpToIndex()` feature will be definitely useful 🙂

**Comment by jerrywell** [comment]
it's the limitation of this package for very long list. : (
please refer to this thread #44 for more detail.

**Comment by rocboronat** [comment]
Thanks for the link with the explanation! 😊

Just for the info: I use this package to go to the actual bottom of a list with dynamic item heights. So I use the regular scroll jump to go to the bottom, and then use the package to do the extra scroll needed to go there. And, as the call returns a Future, is so handy to have the list in opacity 0 until the scroll finished 😊
