### ISSUE TITLE
Scroll Index Listener/Stream from AutoScrollController - Feature Request

### ISSUE THREAD

**Issue by psk907** [quire-io/scroll-to-index#55]
I am currently working on a page with a custom pinned TabBar and a SliverList (fixed count).  This package helped me achieve scrolling on tap to widgets beyond the viewing boundary(and not rendered before), i.e **anchored scrolling**.

However I need a way to have my tab-bar scroll itself as I scroll through various `AutoScrollTag`s, I was thinking that if the controller you provide had a broadcast stream of index changes / a listener or even a `AutoScrollView` that extends Flutter's built-in `ScrollView`'s  , then that would just be great !!

Thanks :)

**Comment by jerrywell** [comment]
you can implement this https://github.com/flutter/flutter/issues/19941#issuecomment-486950990 to get it.

**Comment by psk907** [comment]
Yesss this worked, took me a while to understand it though.

Good workaround 👍🏽

Thanks !
