### ISSUE TITLE
Is it possible to have a jumpTo() function?

### ISSUE THREAD

**Issue by lucyTheSlayer** [quire-io/scroll-to-index#6]
I have a long data list (about 3k+ or more), when use controller.scrollToIndex(),  it took several seconds to finally scroll to the target item. 
The animation duration was set to Duration(milliseconds: 1), and it doesn't seem helpful to reduce the time cost of scrolling animtion.

So is that possible to merely jump to the target item without any scrolling animation?

**Comment by jerrywell** [comment]
try to give a suggested row height to AutoScrollController. this will bring the first search to the closest position. (if the height of your row is fixed.)

```
final controller = AutoScrollController(
  //this given value will bring the scroll offset to the nearest position in fixed row height case
  suggestedRowHeight: 200
);
```

**Comment by lucyTheSlayer** [comment]
The row height is dynamic in my case.  Maybe i should find another way to display my data.

thx
