### ISSUE TITLE
Failed Assertion

### ISSUE THREAD

**Issue by ufobm** [quire-io/scroll-to-index#61]
If I try to scroll to an already visible AutoScrollTag I get this error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:scroll_to_index/scroll_to_index.dart': Failed assertion: line 381 pos 14: '(offsetToLastState?.offset ?? 0) >= 0': ERROR: %%%%%%%%%%%%%%: 2, 1, 1.0, RevealedOffset(offset: -144.0, rect: Rect.fromLTRB(0.0, 144.0, 1182.0, 200.0)), 1
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AutoScrollControllerMixin._forecastMoveUnit (package:scroll_to_index/scroll_to_index.dart:381:14)
#3      AutoScrollControllerMixin._scrollToIndex (package:scroll_to_index/scroll_to_index.dart:271:13)
<asynchronous suspension>

**Comment by jerrywell** [comment]
please try to wrap all row widgets inside the list with `AutoScrollTag` and make sure the index value is sequential value e.g. 0, 1, 2, 3...n.

**Comment by ufobm** [comment]
> please try to wrap all row widgets inside the list with `AutoScrollTag` and make sure the index value is sequential value e.g. 0, 1, 2, 3...n.

They are all already wrapped anche the index value is sequential and unique (I'm using it in a Key). The problem exists only when there's no need to scroll (because the list is short). Otherwise it works (with the same values).
Se attached file for the source code.


[label_colors_conf_form_details.txt](https://github.com/quire-io/scroll-to-index/files/6831428/label_colors_conf_form_details.txt)

**Comment by StigUK** [comment]
I have the same problem on my horizontal list for about 2 months now. And it also appears only when the entire list is sent to the screen. If at least one item does not fit, everything works without errors.

**Comment by arbile26** [comment]
When there is no enough children in the listview I face the same issue.
It would be great if there is a way to check if there are enough children in the listview before triggering scroll to its index.

**Comment by jerrywell** [comment]
please upgrade to 2.1.0 to see if your issue is resolved.

**Comment by arbile26** [comment]
> please upgrade to 2.1.0 to see if your issue is resolved.

Yup! it's resolved.
But when I `scrollToIndex`, the `ListView` disappears for a moment and appears again. This wasn't the case before.
