### ISSUE TITLE
Scroll without animation

### ISSUE THREAD

**Issue by DanieleRigo** [quire-io/scroll-to-index#65]
Hi. In long lists the scrollToIndex can take quite a lot of time to reach the destination, and this is not really a good user experience.  

Is there a way to support the scrollToIndex without animation?

**Comment by jerrywell** [comment]
it's the limitation of this package for very long list. : (
please refer to this thread #44 for more detail.

**Comment by DanieleRigo** [comment]
I understand. 
Thank you for your answer!
