### ISSUE TITLE
在iOS端 滚动视图使用弹簧效果；第一次进入页面，选择滚动到指定tab,会发生弹起来，再回到正常位置

### ISSUE THREAD

**Issue by 9527001** [quire-io/scroll-to-index#67]
修改前
![image](https://user-images.githubusercontent.com/16686832/137678497-7794e863-55ad-4ca0-8cd9-1f5293655d96.png)
修改后
![image](https://user-images.githubusercontent.com/16686832/137678435-b421bc47-7ae0-4fdd-b3c4-52eccf1dd9df.png)

**Comment by jerrywell** [comment]
Fixed by https://github.com/quire-io/scroll-to-index/commit/015f8bdb439640e0de8096b9e15412c6ae7c3dfa
