### ISSUE TITLE
The scroll doesn't take the ListView padding into consideration

### ISSUE THREAD

**Issue by rocboronat** [quire-io/scroll-to-index#68]
Hello! 👋 

One thing there. The plugin was working great until we started painting things below the navbar, on both Android and iOS. Doing it we discovered a small issue.

Right now, we're using a ListView with a bottom padding that has the height of the navbar. That looks great, because the user can scroll the content below the navbar while seeing it. Looks terrific 😄 But, when scrolling to the bottom of the list with `scroll-to-index`, it doesn't take into consideration that bottom padding, so the content appears below the navbar as shown in the screenshot.

Do you have any workaround there?

Thank you so much for the project 😃 

![image](https://user-images.githubusercontent.com/456499/140499938-fe2a28dc-e150-4122-a7d6-2c384b748dce.png)

**Comment by jerrywell** [comment]
Hi @rocboronat 

you can try to the parameter `viewportBoundaryGetter` into scrollController.

```
final controller = AutoScrollController(
  //add this for advanced viewport boundary. e.g. SafeArea
  viewportBoundaryGetter: () => Rect.fromLTRB(0, 0, 0, MediaQuery.of(context).padding.bottom),
);
```

**Comment by rocboronat** [comment]
Oh, looks awesome! I'll give it a try. Thanks, @jerrywell !
