### ISSUE TITLE
Why I am getting this error ? any idea ?

### ISSUE THREAD

**Issue by R1235** [quire-io/scroll-to-index#8]
```
E/flutter ( 6337): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:scroll_to_index/scroll_to_index.dart': Failed assertion: line 332 pos 14: '(offsetToLastState?.offset ?? 0) >= 0': ERROR: %%%%%%%%%%%%%%: 3, 0, 1.0, RevealedOffset(offset: -252.0, rect: Rect.fromLTRB(20.0, 260.0, 340.0, 414.0)), 0
E/flutter ( 6337): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 6337): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 6337): #2      _SimpleAutoScrollController&ScrollController&AutoScrollControllerMixin._forecastMoveUnit (package:scroll_to_index/scroll_to_index.dart:332:14)
E/flutter ( 6337): #3      _SimpleAutoScrollController&ScrollController&AutoScrollControllerMixin._scrollToIndex (package:scroll_to_index/scroll_to_index.dart:251:28)
E/flutter ( 6337): <asynchronous suspension>
E/flutter ( 6337): #4      _SimpleAutoScrollController&ScrollController&AutoScrollControllerMixin.scrollToIndex.<anonymous closure> (package:scroll_to_index/scroll_to_index.dart:195:27)
E/flutter ( 6337): #5      co (package:scroll_to_index/util.dart:37:26)
E/flutter ( 6337): <asynchronous suspension>
E/flutter ( 6337): #6      _SimpleAutoScrollController&ScrollController&AutoScrollControllerMixin.scrollToIndex (package:scroll_to_index/scroll_to_index.dart:195:12)
E/flutter ( 6337): <asynchronous suspension>
E/flutter ( 6337): #7      DemandWidgetApp.getDemandJsonData.<anonymous closure> (package:mer_meta/demandVsSupply.dart:1897:28)
E/flutter ( 6337): #8      State.setState (package:flutter/src/widgets/framework.dart:1127:30)
E/flutter ( 6337): #9      DemandWidgetApp.getDemandJsonData (package:mer_meta/demandVsSupply.dart:1868:5)
E/flutter ( 6337): #10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 6337): #11     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 6337): #12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6337): #13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 6337): #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 6337): #15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 6337): #16     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 6337): #17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 6337): #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 6337): #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 6337): #20     BusinessLogic.methodGetDynamic (package:mer_meta/businessLogic.dart)
E/flutter ( 6337): #21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 6337): #22     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 6337): #23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6337): #24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 6337): #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 6337): #26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 6337): #27     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 6337): #28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 6337): #29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 6337): #30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 6337): #31     _withClient (package:http/http.dart)
E/flutter ( 6337): #32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 6337): #33     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 6337): #34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6337): #35     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 6337): #36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 6337): #37     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 6337): #38     Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter ( 6337): #39     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter ( 6337): #40     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6337): #41     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6337): #42     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6337): #43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6337): #44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6337): #45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 6337):
```

**Comment by jerrywell** [comment]
may you post the reproduce sample?
this assertion was used to check the issue of move algorithm at the early stage. 
not sure if we need to keep it now.

**Comment by R1235** [comment]
My Scenario is:
I have 3 screens A, B, C
Screen A has List of values, upon selecting a list item it should redirect to screen B (which has list of items) to a particular position.
In screen B if I select an item it should redirect to screen C (where if I click on submit in screen C) it should redirect back to screen B to a particular position.

My Issue is:
When am redirecting from Screen C to Screen B some times scrollToIndex is not going to the particular position and getting the above mentioned error.


Code in Screen B:
class DemandWidgetApp extends State<DemandTab> {
 AutoScrollController scrollController;

 @override
  void initState() {
    super.initState();
 scrollController = AutoScrollController(
        viewportBoundaryGetter: () =>
            Rect.fromLTRB(0, 0, 0, MediaQuery.of(context).padding.bottom),
        axis: scrollDirection);
}

Future<List> getDemandJsonData([int status]) async {

    List filtered = _demandFilterPriority
        .where((Map sta) => sta['value'] == status)
        .toList();
    if (filtered.length > 0) {
      _seletedStatus = filtered[0]['text'].toString();
    }
    var result = await new BusinessLogic().methodGetDynamic(status == 0
        ? 'demand?priority=null&demand_eng_designation=NaN'
        : 'demand?priority=' +
            status.toString() +
            '&demand_eng_designation=' +
            designationId);
    setState(() {
      if (result == null) {
        _searchResult = null;
        _demandListAll = null;
      } else {
        var dataConvertedToJSON = json.decode(result);
        _demandListAll = (dataConvertedToJSON["data"] as List)
            .map<DemandData>((json) => new DemandData.fromJson(json))
            .toList();
        _searchResult = (dataConvertedToJSON["data"] as List)
            .map<DemandData>((json) => new DemandData.fromJson(json))
            .toList();
      }
      if (demandSelectedPosition != 0) {
        scrollController.scrollToIndex(demandSelectedPosition,
            preferPosition: AutoScrollPosition.begin);
        scrollController.highlight(demandSelectedPosition);
      }
       
      for (int i = 0; i < _searchResult.length; i++) {
        if (editDemandReqID == _searchResult[i].requestID) {
          _searchResult[i].supplyinDemandData.demandRequestIdinSupply =
              demandRequestId;
            print(i);
**// this is where am getting error**
          **scrollController.scrollToIndex(i,
              preferPosition: AutoScrollPosition.begin);
          scrollController.highlight(i);**
        }
      }

      for (int i = 0; i < _searchResult.length; i++) {
        if (demandRequestId == _searchResult[i].requestID) {
          _searchResult[i].supplyinDemandData.demandRequestIdinSupply =
              demandRequestId;
          /*   scrollController = AutoScrollController(
              viewportBoundaryGetter: () =>
                  Rect.fromLTRB(0, 0, 0, MediaQuery.of(context).padding.bottom),
              axis: scrollDirection);
 */
          scrollController.scrollToIndex(i,
              preferPosition: AutoScrollPosition.begin);
          scrollController.highlight(i);
          requestIdSharedPreference.setInt('REQUEST_ID_SHARED_PREFERENCE', 0);
        } else {
          requestIdSharedPreference.setInt('REQUEST_ID_SHARED_PREFERENCE', 0);
        }
      }
      _prefsDemandDesignationID.setString("DEMAND_DESIGNATION_ID", "NaN");
    });
    return _searchResult;
  }




Widget _displayDemandData(int position) {
    return new Container(
        child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
          Row(
            children: <Widget>[
              CircleAvatar(
                radius: 15.0,
                backgroundColor: Colors.amber,
                foregroundColor: Colors.white,
                child: Text((position + 1).toString()),
              ),
              Container(
                padding: EdgeInsets.only(left: 10),
                child: Row(children: <Widget>[
                  Row(
                    children: <Widget>[
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Container(
                              width: 230,
                              child: _searchResult[position].priorityId == 1
                                  ? Text(_searchResult[position].priority,
                                      style: TextStyle(
                                          color: metaThemeData.dividerColor))
                                  : (_searchResult[position].priorityId == 2
                                      ? Text(_searchResult[position].priority,
                                          style: TextStyle(
                                              color:
                                                  metaThemeData.highlightColor))
                                      : Text(_searchResult[position].priority,
                                          style: TextStyle(
                                              color:
                                                  metaThemeData.splashColor)))),
                          InkWell(
                            
                              child: Text(_searchResult[position].projectName,
                                  style: TextStyle(
                                      color: Colors.blue,
                                      decoration: TextDecoration.underline,
                                      decorationStyle:
                                          TextDecorationStyle.dotted))),
                        ],
                      ),
                    ],
                  ),
                ]),
              ),
            ],
          ),
          SizedBox(height: 5),
          Row(
            children: <Widget>[
              SizedBox(
                width: 134,
                child: Text('Project Role'),
              ),
              Text(
                ' : ' + _searchResult[position].projectRole,
              )
            ],
          ),
          SizedBox(height: 5),
          Row(
            children: <Widget>[
              SizedBox(
                width: 134,
                child: Text('Bandwidth Req'),
              ),
              Text(' : ' +
                  _searchResult[position].bandWidthRequired.toString() +
                  "%")
            ],
          ),
          SizedBox(height: 5),
          Row(children: <Widget>[
            SizedBox(
              width: 134,
              child: Text('Req Start Date'),
            ),
            Text(' : ' +
                formatDate(DateTime.parse(_searchResult[position].startDate),
                    [M, ' ', d, ', ', yyyy])),
          ]),
          displayEditDeleteInfoButtons(position),
        ]));
  }

**Comment by jerrywell** [comment]
sorry, it's still can't reproduce this issue without a clear runnable sample. 

this assertion is actually telling us the right offset the scrollController should scroll to. and it's not possible within a minus value (except the overscroll). so that's why there is a assertion. i didn't see this kind of error recent years when using this package. for the production release, the assertion won't block the whole scrolling. that is, it "may" cause a over scroll effect and move to offset 0, which is wrong position due to the Flutter's calculation function(please see RenderAbstractViewport's getOffsetToReveal()).

without the reproduce sample, i can't fix it or post the issue to Flutter team. sorry about that. : (

**Comment by R1235** [comment]
@jerrywell thank you for the reply. My issue got fixed. I just cleared and loaded the list each time when the page is reloading. This solution fixed my issue.
