### ISSUE TITLE
Why can't forecast the move range when `moveTarget` is negative?

### ISSUE THREAD

**Issue by MiniSuperDev** [quire-io/scroll-to-index#94]
Hello, I have a case when I need to comment this 2 lines to be able to scroll to the index because the `moveTarget` is negative.
https://github.com/quire-io/scroll-to-index/blob/d7ce91456407a42e3337fdbe959f585e1e5b51f8/lib/scroll_to_index.dart#L272-L273
![image](https://user-images.githubusercontent.com/105388540/168875192-fafd79b0-e381-4c32-a1d0-7be7833b6aa1.png)

I don't know if you should remove it, so I'm asking if you should remove it, since I don't know in what cases being negative it wouldn't work?

I leave you a [gist](https://gist.github.com/MiniSuperDev/f048141d47abc16d5de196f263bf9223) with an example where it only works if you comment those 2 lines.

To reproduce the error, first press the button 1 that goes to last index, and then the second button that go to index 3, and you notice when want to go to index 3, the `moveTarget` is negative so we need to comment those 2 lines.
![image](https://user-images.githubusercontent.com/105388540/168874995-5089600a-5082-42f8-b475-553d6d712ec6.png)

Thank you

**Comment by jerrywell** [comment]
thanks for the reproduce example : ) this issue has been fixed.
