### ISSUE TITLE
scroll_to_index-2.1.1: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null

### ISSUE THREAD

**Issue by Nike682631** [quire-io/scroll-to-index#96]
I'm trying to implement integration testing for my flutter app but I'm getting this error when writing something very straightforward.

```ERROR: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/scroll_to_index-2.1.1/lib/scroll_to_index.dart:358:57: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.```

Please help me in resolving this error.

**Comment by jerrywell** [comment]
fixed by https://github.com/quire-io/scroll-to-index/commit/4490a7787762155436a50518062638163ed04f5d
